###################################################################################################################3
####      PCIE4REC_V10
####           IOVerify-MS_v4.tcl
####                                    ZHAOCHAO
####                                    2017-12-06
#############################################################################################
#### add 4 ddr2 pin map
####                                    2017-12-06
#############################################################################################
#### add 2 sfp pin map
####                                    2017-12-06
#############################################################################################
#### add AD9653, PEX8311, RF_CHANEL pin map
####                                    2017-12-08
#############################################################################################
#### fit for 5CGXFC9 	SCH-Version: sch-20180714
#### 									2018-07-14
#############################################################################################
#### fit for 5CGXFC9 	SCH-Version: sch-20181114
#### 									2018-11-14
#############################################################################################
#### fit SCH-Version: sch-20181118
#### 									2018-11-18
#############################################################################################
#### CLOCK 

	set_location_assignment PIN_R20 -to BOARD_CLK[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to BOARD_CLK[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to BOARD_CLK[0]

	set_location_assignment PIN_G15 -to EXT_CLK[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to EXT_CLK[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to EXT_CLK[0]

####
################################################################################
#### PERIPHERAL

	set_location_assignment PIN_V25 -to IDC_LO[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to IDC_LO[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to IDC_LO[0]
	
	set_location_assignment PIN_W26 -to IDC_SAMPLE[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to IDC_SAMPLE[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to IDC_SAMPLE[0]
	
	set_location_assignment PIN_Y26 -to GPIO[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to GPIO[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to GPIO[0]
	set_location_assignment PIN_AA26 -to GPIO[1]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to GPIO[1]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to GPIO[1]
	set_location_assignment PIN_Y25 -to GPIO[2]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to GPIO[2]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to GPIO[2]
	set_location_assignment PIN_AB26 -to GPIO[3]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to GPIO[3]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to GPIO[3]

	set_location_assignment PIN_AB25 -to TEST_LED[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to TEST_LED[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to TEST_LED[0]
	set_location_assignment PIN_AC25 -to TEST_LED[1]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to TEST_LED[1]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to TEST_LED[1]
	set_location_assignment PIN_AD25 -to TEST_LED[2]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to TEST_LED[2]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to TEST_LED[2]
	set_location_assignment PIN_R23  -to TEST_LED[3]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to TEST_LED[3]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to TEST_LED[3]

	set_location_assignment PIN_W25 -to DE18E01[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to DE18E01[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to DE18E01[0]
	
####
#####################################################################################
#### DDR2 A
	set_location_assignment PIN_AF7  -to ddr2a_ck[0] 
	set_location_assignment PIN_AF8  -to ddr2a_ckn[0]  

	set_location_assignment PIN_AD10 -to ddr2a_cke[0]  
	set_location_assignment PIN_AF18 -to ddr2a_csn[0] 
	set_location_assignment PIN_AF16 -to ddr2a_rasn[0] 
	set_location_assignment PIN_AD13 -to ddr2a_casn[0] 
	set_location_assignment PIN_V10  -to ddr2a_wen[0]   

	set_location_assignment PIN_AC15 -to ddr2a_addr[0]  
	set_location_assignment PIN_V9   -to ddr2a_addr[1]   
	set_location_assignment PIN_AC13 -to ddr2a_addr[2]  
	set_location_assignment PIN_R8   -to ddr2a_addr[3]   
	set_location_assignment PIN_AC14 -to ddr2a_addr[4]   
	set_location_assignment PIN_W8   -to ddr2a_addr[5]   
	set_location_assignment PIN_AB12 -to ddr2a_addr[6]   
	set_location_assignment PIN_U7   -to ddr2a_addr[7]    
	set_location_assignment PIN_Y13  -to ddr2a_addr[8]   
	set_location_assignment PIN_AE9  -to ddr2a_addr[9]   
	set_location_assignment PIN_U9   -to ddr2a_addr[10]   
	set_location_assignment PIN_AF9  -to ddr2a_addr[11]   
	set_location_assignment PIN_AA6  -to ddr2a_addr[12]   

	set_location_assignment PIN_AE13 -to ddr2a_ba[0]    
	set_location_assignment PIN_Y9   -to ddr2a_ba[1]    
	set_location_assignment PIN_AB10 -to ddr2a_ba[2]   

	# DQ2B  (BANK 3B)
	set_location_assignment PIN_AC9  -to ddr2a_dq[0] 
	set_location_assignment PIN_AC8  -to ddr2a_dq[1]
	set_location_assignment PIN_W11  -to ddr2a_dq[2]
	set_location_assignment PIN_Y10  -to ddr2a_dq[3]
	set_location_assignment PIN_Y11  -to ddr2a_dq[4]
	set_location_assignment PIN_W10  -to ddr2a_dq[5]
	set_location_assignment PIN_AC10 -to ddr2a_dq[6]
	set_location_assignment PIN_AB11 -to ddr2a_dq[7]
	set_location_assignment PIN_R11  -to ddr2a_dqs[0]   
    # DQ4B   (BANK 4A)
	set_location_assignment PIN_Y14  -to ddr2a_dq[8]
	set_location_assignment PIN_AD11 -to ddr2a_dq[9]
	set_location_assignment PIN_AD12 -to ddr2a_dq[10]
	set_location_assignment PIN_AF12 -to ddr2a_dq[11]
	set_location_assignment PIN_AE10 -to ddr2a_dq[12]
	set_location_assignment PIN_W12  -to ddr2a_dq[13]
	set_location_assignment PIN_AF11 -to ddr2a_dq[14]
	set_location_assignment PIN_AA14 -to ddr2a_dq[15]
	set_location_assignment PIN_V13  -to ddr2a_dqs[1]  

	set_location_assignment PIN_AE15 -to ddr2a_odt[0]   

	set_location_assignment PIN_AC22  -to ddr2a_oct_rzqin[0]
	set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2a_oct_rzqin[0] 
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2a_oct_rzqin[0]

####
################################################################################
#### DDR2 B

	set_location_assignment PIN_AE14  -to ddr2b_ck[0]   
	set_location_assignment PIN_AF14  -to ddr2b_ckn[0]  

	set_location_assignment PIN_V19   -to ddr2b_cke[0]   
	set_location_assignment PIN_AC24  -to ddr2b_csn[0] 
	set_location_assignment PIN_AE23  -to ddr2b_rasn[0] 
	set_location_assignment PIN_AF24  -to ddr2b_casn[0]  
	set_location_assignment PIN_V20   -to ddr2b_wen[0]  
		
	set_location_assignment PIN_AD23  -to ddr2b_addr[0]   
	set_location_assignment PIN_W17   -to ddr2b_addr[1]   
	set_location_assignment PIN_AF22  -to ddr2b_addr[2]   
	set_location_assignment PIN_AB19  -to ddr2b_addr[3]   
	set_location_assignment PIN_Y24   -to ddr2b_addr[4]   
	set_location_assignment PIN_W16   -to ddr2b_addr[5]   
	set_location_assignment PIN_AD21  -to ddr2b_addr[6]   
	set_location_assignment PIN_AD18  -to ddr2b_addr[7]   
	set_location_assignment PIN_AF23  -to ddr2b_addr[8]   
	set_location_assignment PIN_AE16  -to ddr2b_addr[9]  
	set_location_assignment PIN_Y20   -to ddr2b_addr[10]   
	set_location_assignment PIN_U20   -to ddr2b_addr[11]   
	set_location_assignment PIN_AA16  -to ddr2b_addr[12]   

	set_location_assignment PIN_AD22  -to ddr2b_ba[0]   
	set_location_assignment PIN_W18   -to ddr2b_ba[1]   
	set_location_assignment PIN_AC20  -to ddr2b_ba[2]    
# DQ6B  (BANK 4A)
	set_location_assignment PIN_AC17  -to ddr2b_dq[0] 
	set_location_assignment PIN_AF19  -to ddr2b_dq[1]
	set_location_assignment PIN_AD17  -to ddr2b_dq[2]
	set_location_assignment PIN_AB17  -to ddr2b_dq[3]
	set_location_assignment PIN_AF21  -to ddr2b_dq[4]
	set_location_assignment PIN_AD16  -to ddr2b_dq[5]
	set_location_assignment PIN_AC18  -to ddr2b_dq[6]
	set_location_assignment PIN_AE20  -to ddr2b_dq[7]
	set_location_assignment PIN_V15   -to ddr2b_dqs[0]   
# DQ8B  (BANK 4A)
	set_location_assignment PIN_AE25  -to ddr2b_dq[8]
	set_location_assignment PIN_Y18   -to ddr2b_dq[9]
	set_location_assignment PIN_AC19  -to ddr2b_dq[10]
	set_location_assignment PIN_AA18  -to ddr2b_dq[11]
	set_location_assignment PIN_AB22  -to ddr2b_dq[12]
	set_location_assignment PIN_AA21  -to ddr2b_dq[13]
	set_location_assignment PIN_Y19   -to ddr2b_dq[14]
	set_location_assignment PIN_AE26  -to ddr2b_dq[15]
	set_location_assignment PIN_V18   -to ddr2b_dqs[1] 

	set_location_assignment PIN_AD26   -to ddr2b_odt[0]   

	#set_location_assignment PIN_AE11  -to ddr2b_oct_rzqin[0]
	#set_location_assignment PIN_AC22  -to ddr2b_oct_rzqin[0]
	#set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2b_oct_rzqin[0] 
	#set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2b_oct_rzqin[0]

####
######################################################################################
#### SFP A

	set_location_assignment PIN_T2 -to SFPA_RX[0]
	set_instance_assignment -name IO_STANDARD "1.5-V PCML"  -to SFPA_RX[0]
	# set_location_assignment PIN_T1 -to "SFPA_RX[0](n)"

	set_location_assignment PIN_P2 -to SFPA_TD[0]
	set_instance_assignment -name IO_STANDARD "1.5-V PCML"  -to SFPA_TD[0]
	# set_location_assignment PIN_P1 -to "SFPA_TD[0](n)"

	set_location_assignment PIN_N7 -to SFPA_CLK[0]
	set_instance_assignment -name IO_STANDARD "LVDS"  -to SFPA_CLK[0]
	# set_location_assignment PIN_P6 -to "SFPA_CLK[0](n)"

	set_location_assignment PIN_M11 -to SFPA_TXDisable[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to SFPA_TXDisable[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to SFPA_TXDisable[0]
	set_location_assignment PIN_L8  -to SFPA_TXFault[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to SFPA_TXFault[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to SFPA_TXFault[0]
	set_location_assignment PIN_N12 -to SFPA_LOS[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to SFPA_LOS[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to SFPA_LOS[0]
	set_location_assignment PIN_L7  -to SFPA_MOD0[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to SFPA_MOD0[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to SFPA_MOD0[0]
	set_location_assignment PIN_M12 -to SFPA_MOD1[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to SFPA_MOD1[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to SFPA_MOD1[0]
	set_location_assignment PIN_M9 -to SFPA_MOD2[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to SFPA_MOD2[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to SFPA_MOD2[0]

####
########################################################################################
#### SFP B

	set_location_assignment PIN_M2 -to SFPB_RX[0]
	set_instance_assignment -name IO_STANDARD "1.5-V PCML"  -to SFPB_RX[0]
	# set_location_assignment PIN_T1 -to "SFPB_RX[0](n)"

	set_location_assignment PIN_K2 -to SFPB_TD[0]
	set_instance_assignment -name IO_STANDARD "1.5-V PCML"  -to SFPB_TD[0]
	# set_location_assignment PIN_P1 -to "SFPB_TD[0](n)"

	#set_location_assignment PIN_N7 -to SFPB_CLK[0]
	#set_instance_assignment -name IO_STANDARD "LVDS"  -to SFPB_CLK[0]
	# set_location_assignment PIN_P6 -to "SFPB_CLK[0](n)"

	# set_location_assignment PIN_AF18 -to SFPB_CLK_OUT
	# set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to SFPB_CLK_OUT[0]
	# set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to SFPB_CLK_OUT[0]

	set_location_assignment PIN_K9 -to SFPB_TXDisable[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to SFPB_TXDisable[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to SFPB_TXDisable[0]
	set_location_assignment PIN_K10 -to SFPB_TXFault[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to SFPB_TXFault[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to SFPB_TXFault[0]
	set_location_assignment PIN_K6 -to SFPB_LOS[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to SFPB_LOS[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to SFPB_LOS[0]
	set_location_assignment PIN_K8 -to SFPB_MOD0[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to SFPB_MOD0[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to SFPB_MOD0[0]
	set_location_assignment PIN_L9 -to SFPB_MOD1[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to SFPB_MOD1[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to SFPB_MOD1[0]
	set_location_assignment PIN_L11 -to SFPB_MOD2[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to SFPB_MOD2[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to SFPB_MOD2[0]

####
#######################################################################################################33
#### RF_CHANEL CTL

# CHA 
	set_location_assignment PIN_J25 -to CHA_AMP1_THR[0]
	set_instance_assignment -name IO_STANDARD "2.5V" -to CHA_AMP1_THR[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to CHA_AMP1_THR[0]
	set_location_assignment PIN_J26 -to CHA_AMP1_BYPASS[0]
	set_instance_assignment -name IO_STANDARD "2.5V" -to CHA_AMP1_BYPASS[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to CHA_AMP1_BYPASS[0]
	set_location_assignment PIN_J21 -to CHA_AMP2_THR[0]
	set_instance_assignment -name IO_STANDARD "2.5V" -to CHA_AMP2_THR[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to CHA_AMP2_THR[0]
	set_location_assignment PIN_J20 -to CHA_AMP2_BYPASS[0]
	set_instance_assignment -name IO_STANDARD "2.5V" -to CHA_AMP2_BYPASS[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to CHA_AMP2_BYPASS[0]
	
	set_location_assignment PIN_V23 -to CHA_5201_CS[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to CHA_5201_CS[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to CHA_5201_CS[0]
	set_location_assignment PIN_V24 -to CHA_5201_SCLK[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to CHA_5201_SCLK[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to CHA_5201_SCLK[0]
	set_location_assignment PIN_U24 -to CHA_5201_SDIO[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to CHA_5201_SDIO[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to CHA_5201_SDIO[0]
	set_location_assignment PIN_AA24 -to CHA_5201_LATCH[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to CHA_5201_SDIO[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to CHA_5201_LATCH[0]

# CHB
	set_location_assignment PIN_H25 -to CHB_AMP1_THR[0]
	set_instance_assignment -name IO_STANDARD "2.5V" -to CHB_AMP1_THR[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to CHB_AMP1_THR[0]
	set_location_assignment PIN_H23 -to CHB_AMP1_BYPASS[0]
	set_instance_assignment -name IO_STANDARD "2.5V" -to CHB_AMP1_BYPASS[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to CHB_AMP1_BYPASS[0]
	set_location_assignment PIN_F24 -to CHB_AMP2_THR[0]
	set_instance_assignment -name IO_STANDARD "2.5V" -to CHB_AMP2_THR[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to CHB_AMP2_THR[0]
	set_location_assignment PIN_G25 -to CHB_AMP2_BYPASS[0]
	set_instance_assignment -name IO_STANDARD "2.5V" -to CHB_AMP2_BYPASS[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to CHB_AMP2_BYPASS[0]
	
	set_location_assignment PIN_U26 -to CHB_5201_CS[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to CHB_5201_CS[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to CHB_5201_CS[0]
	set_location_assignment PIN_R25 -to CHB_5201_SCLK[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to CHB_5201_SCLK[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to CHB_5201_SCLK[0]
	set_location_assignment PIN_R26 -to CHB_5201_SDIO[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to CHB_5201_SDIO[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to CHB_5201_SDIO[0]
	set_location_assignment PIN_T26 -to CHB_5201_LATCH[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to CHB_5201_LATCH[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to CHB_5201_LATCH[0]
	
# CHC
	set_location_assignment PIN_G22 -to CHC_AMP1_THR[0]
	set_instance_assignment -name IO_STANDARD "2.5V" -to CHC_AMP1_THR[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to CHC_AMP1_THR[0]
	set_location_assignment PIN_F22 -to CHC_AMP1_BYPASS[0]
	set_instance_assignment -name IO_STANDARD "2.5V" -to CHC_AMP1_BYPASS[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to CHC_AMP1_BYPASS[0]
	set_location_assignment PIN_D26 -to CHC_AMP2_THR[0]
	set_instance_assignment -name IO_STANDARD "2.5V" -to CHC_AMP2_THR[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to CHC_AMP2_THR[0]
	set_location_assignment PIN_F23 -to CHC_AMP2_BYPASS[0]
	set_instance_assignment -name IO_STANDARD "2.5V" -to CHC_AMP2_BYPASS[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to CHC_AMP2_BYPASS[0]
	
	set_location_assignment PIN_T24 -to CHC_5201_CS[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to CHC_5201_CS[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to CHC_5201_CS[0]
	set_location_assignment PIN_R24 -to CHC_5201_SCLK[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to CHC_5201_SCLK[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to CHC_5201_SCLK[0]
	set_location_assignment PIN_T21 -to CHC_5201_SDIO[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to CHC_5201_SDIO[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to CHC_5201_SDIO[0]
	set_location_assignment PIN_N25 -to CHC_5201_LATCH[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to CHC_5201_LATCH[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to CHC_5201_LATCH[0]

# CHD
	set_location_assignment PIN_E24 -to CHD_AMP1_THR[0]
	set_instance_assignment -name IO_STANDARD "2.5V" -to CHD_AMP1_THR[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to CHD_AMP1_THR[0]
	set_location_assignment PIN_E23 -to CHD_AMP1_BYPASS[0]
	set_instance_assignment -name IO_STANDARD "2.5V" -to CHD_AMP1_BYPASS[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to CHD_AMP1_BYPASS[0]
	set_location_assignment PIN_E21 -to CHD_AMP2_THR[0]
	set_instance_assignment -name IO_STANDARD "2.5V" -to CHD_AMP2_THR[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to CHD_AMP2_THR[0]
	set_location_assignment PIN_D22 -to CHD_AMP2_BYPASS[0]
	set_instance_assignment -name IO_STANDARD "2.5V" -to CHD_AMP2_BYPASS[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to CHD_AMP2_BYPASS[0]
	
	set_location_assignment PIN_P26 -to CHD_5201_CS[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to CHD_5201_CS[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to CHD_5201_CS[0]
	set_location_assignment PIN_P21 -to CHD_5201_SCLK[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to CHD_5201_SCLK[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to CHD_5201_SCLK[0]
	set_location_assignment PIN_P23 -to CHD_5201_SDIO[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to CHD_5201_SDIO[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to CHD_5201_SDIO[0]
	set_location_assignment PIN_P22 -to CHD_5201_LATCH[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to CHD_5201_LATCH[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to CHD_5201_LATCH[0]

####
#######################################################################################################33
#### AD9653

	set_location_assignment PIN_F26 -to AD_CLK[0]
	set_instance_assignment -name IO_STANDARD "LVDS" -to AD_CLK[0]
#	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to AD_CLK[0]
	
	set_location_assignment PIN_Y23 -to AD_SYNC[0]
	set_instance_assignment -name IO_STANDARD "1.8V" -to AD_SYNC[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to AD_SYNC[0]
	set_location_assignment PIN_V22 -to AD_CSB[0]
	set_instance_assignment -name IO_STANDARD "1.8V" -to AD_CSB[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to AD_CSB[0]
	set_location_assignment PIN_U22 -to AD_SCLK[0]
	set_instance_assignment -name IO_STANDARD "1.8V" -to AD_SCLK[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to AD_SCLK[0]
	set_location_assignment PIN_U19 -to AD_SDIO[0]
	set_instance_assignment -name IO_STANDARD "1.8V" -to AD_SDIO[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to AD_SDIO[0]
	
	
	set_location_assignment PIN_L22 -to AD_FCO[0]
	set_instance_assignment -name IO_STANDARD "LVDS" -to AD_FCO[0]
#	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to AD_FCO[0]
	set_location_assignment PIN_K25 -to AD_DCO[0]
	set_instance_assignment -name IO_STANDARD "LVDS" -to AD_DCO[0]
#	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to AD_DCO[0]
	set_location_assignment PIN_M25 -to AD_CHA_D0[0]
	set_instance_assignment -name IO_STANDARD "LVDS"  -to AD_CHA_D0[0]
	set_location_assignment PIN_N23 -to AD_CHA_D1[0]
	set_instance_assignment -name IO_STANDARD "LVDS"  -to AD_CHA_D1[0]
	set_location_assignment PIN_N24 -to AD_CHB_D0[0]
	set_instance_assignment -name IO_STANDARD "LVDS"  -to AD_CHB_D0[0]
	set_location_assignment PIN_L23 -to AD_CHB_D1[0]
	set_instance_assignment -name IO_STANDARD "LVDS"  -to AD_CHB_D1[0]
	set_location_assignment PIN_K24 -to AD_CHC_D0[0]
	set_instance_assignment -name IO_STANDARD "LVDS"  -to AD_CHC_D0[0]
	set_location_assignment PIN_H19 -to AD_CHC_D1[0] 
	set_instance_assignment -name IO_STANDARD "LVDS"  -to AD_CHC_D1[0]
	set_location_assignment PIN_H22 -to AD_CHD_D0[0]
	set_instance_assignment -name IO_STANDARD "LVDS"  -to AD_CHD_D0[0]
	set_location_assignment PIN_G20 -to AD_CHD_D1[0]
	set_instance_assignment -name IO_STANDARD "LVDS"  -to AD_CHD_D1[0]
	
####
#######################################################################################################33
#### PEX8311

	set_location_assignment PIN_D18 -to PEX8311_LD[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LD[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LD[0]
	set_location_assignment PIN_C18 -to PEX8311_LD[1]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LD[1]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LD[1]
	set_location_assignment PIN_C19 -to PEX8311_LD[2]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LD[2]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LD[2]
	set_location_assignment PIN_A17 -to PEX8311_LD[3]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LD[3]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LD[3]
	set_location_assignment PIN_A18 -to PEX8311_LD[4]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LD[4]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LD[4]
	set_location_assignment PIN_D17 -to PEX8311_LD[5]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LD[5]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LD[5]
	set_location_assignment PIN_B19 -to PEX8311_LD[6]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LD[6]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LD[6]
	set_location_assignment PIN_A19 -to PEX8311_LD[7]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LD[7]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LD[7]
	set_location_assignment PIN_J16 -to PEX8311_LD[8]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LD[8]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LD[8]
	set_location_assignment PIN_G16 -to PEX8311_LD[9]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LD[9]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LD[9]
	set_location_assignment PIN_C17 -to PEX8311_LD[10]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LD[10]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LD[10]
	set_location_assignment PIN_B17 -to PEX8311_LD[11]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LD[11]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LD[11]
	set_location_assignment PIN_F16 -to PEX8311_LD[12]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LD[12]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LD[12]
	set_location_assignment PIN_C15 -to PEX8311_LD[13]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LD[13]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LD[13]
	set_location_assignment PIN_D16 -to PEX8311_LD[14]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LD[14]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LD[14]
	set_location_assignment PIN_G12 -to PEX8311_LD[15]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LD[15]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LD[15]
	set_location_assignment PIN_A14 -to PEX8311_LD[16]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LD[16]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LD[16]
	set_location_assignment PIN_C14 -to PEX8311_LD[17]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LD[17]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LD[17]
	set_location_assignment PIN_D15 -to PEX8311_LD[18]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LD[18]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LD[18]
	set_location_assignment PIN_D13 -to PEX8311_LD[19]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LD[19]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LD[19]
	set_location_assignment PIN_H14 -to PEX8311_LD[20]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LD[20]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LD[20]
	set_location_assignment PIN_H13 -to PEX8311_LD[21]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LD[21]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LD[21]
	set_location_assignment PIN_H15 -to PEX8311_LD[22]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LD[22]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LD[22]
	set_location_assignment PIN_C13 -to PEX8311_LD[23]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LD[23]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LD[23]
	set_location_assignment PIN_L12 -to PEX8311_LD[24]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LD[24]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LD[24]
	set_location_assignment PIN_F12 -to PEX8311_LD[25]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LD[25]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LD[25]
	set_location_assignment PIN_E13 -to PEX8311_LD[26]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LD[26]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LD[26]
	set_location_assignment PIN_B12 -to PEX8311_LD[27]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LD[27]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LD[27]
	set_location_assignment PIN_A11 -to PEX8311_LD[28]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LD[28]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LD[28]
	set_location_assignment PIN_A13 -to PEX8311_LD[29]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LD[29]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LD[29]
	set_location_assignment PIN_J11 -to PEX8311_LD[30]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LD[30]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LD[30]
	set_location_assignment PIN_K11 -to PEX8311_LD[31]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LD[31]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LD[31]
	
	set_location_assignment PIN_E15 -to PEX8311_DP[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_DP[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_DP[0]
	set_location_assignment PIN_B15 -to PEX8311_DP[1]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_DP[1]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_DP[1]
	set_location_assignment PIN_B14 -to PEX8311_DP[2]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_DP[2]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_DP[2]
	set_location_assignment PIN_J12 -to PEX8311_DP[3]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_DP[3]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_DP[3]
	
	
	# TCL: PEX8311_LA[0:29] -> SCH:PEX8311 PORT LA[2:31]
	set_location_assignment PIN_A9  -to PEX8311_LA[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LA[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LA[0]
	set_location_assignment PIN_C10 -to PEX8311_LA[1]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LA[1]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LA[1]
	set_location_assignment PIN_D11 -to PEX8311_LA[2]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LA[2]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LA[2]
	set_location_assignment PIN_A8  -to PEX8311_LA[3]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LA[3]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LA[3]
	set_location_assignment PIN_B9  -to PEX8311_LA[4]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LA[4]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LA[4]
	set_location_assignment PIN_B11 -to PEX8311_LA[5]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LA[5]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LA[5]
	set_location_assignment PIN_C12 -to PEX8311_LA[6]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LA[6]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LA[6]
	set_location_assignment PIN_D8  -to PEX8311_LA[7]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LA[7]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LA[7]
	set_location_assignment PIN_E10 -to PEX8311_LA[8]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LA[8]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LA[8]
	set_location_assignment PIN_G10 -to PEX8311_LA[9]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LA[9]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LA[9]
	set_location_assignment PIN_E11 -to PEX8311_LA[10]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LA[10]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LA[10]
	set_location_assignment PIN_D7  -to PEX8311_LA[11]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LA[11]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LA[11]
	set_location_assignment PIN_H9  -to PEX8311_LA[12]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LA[12]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LA[12]
	set_location_assignment PIN_H10 -to PEX8311_LA[13]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LA[13]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LA[13]
	set_location_assignment PIN_B6  -to PEX8311_LA[14]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LA[14]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LA[14]
	set_location_assignment PIN_H8  -to PEX8311_LA[15]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LA[15]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LA[15]
	set_location_assignment PIN_A5  -to PEX8311_LA[16]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LA[16]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LA[16]
	set_location_assignment PIN_C7  -to PEX8311_LA[17]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LA[17]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LA[17]
	set_location_assignment PIN_A7  -to PEX8311_LA[18]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LA[18]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LA[18]
	set_location_assignment PIN_D6  -to PEX8311_LA[19]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LA[19]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LA[19]
	set_location_assignment PIN_E9  -to PEX8311_LA[20]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LA[20]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LA[20]
	set_location_assignment PIN_B7  -to PEX8311_LA[21]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LA[21]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LA[21]
	set_location_assignment PIN_J7  -to PEX8311_LA[22]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LA[22]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LA[22]
	set_location_assignment PIN_F7  -to PEX8311_LA[23]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LA[23]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LA[23]
	set_location_assignment PIN_E6  -to PEX8311_LA[24]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LA[24]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LA[24]
	set_location_assignment PIN_G7  -to PEX8311_LA[25]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LA[25]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LA[25]
	set_location_assignment PIN_F6  -to PEX8311_LA[26]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LA[26]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LA[26]
	set_location_assignment PIN_H7  -to PEX8311_LA[27]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LA[27]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LA[27]
	set_location_assignment PIN_G6  -to PEX8311_LA[28]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LA[28]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LA[28]
	set_location_assignment PIN_J8  -to PEX8311_LA[29]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LA[29]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LA[29]
	
	set_location_assignment PIN_B10 -to PEX8311_LBE[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LBE[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LBE[0]
	set_location_assignment PIN_J10 -to PEX8311_LBE[1]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LBE[1]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LBE[1]
	set_location_assignment PIN_D10 -to PEX8311_LBE[2]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LBE[2]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LBE[2]
	set_location_assignment PIN_C9 -to PEX8311_LBE[3]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LBE[3]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LBE[3]
	
	set_location_assignment PIN_A22 -to PEX8311_LRESET[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LRESET[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LRESET[0]
	set_location_assignment PIN_C20 -to PEX8311_ADS[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_ADS[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_ADS[0]
	set_location_assignment PIN_C22 -to PEX8311_BLAST[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_BLAST[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_BLAST[0]
	set_location_assignment PIN_H18 -to PEX8311_READY[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_READY[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_READY[0]
	set_location_assignment PIN_A16 -to PEX8311_LSERR[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LSERR[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LSERR[0]
	set_location_assignment PIN_E19 -to PEX8311_EOT[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_EOT[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_EOT[0]
	set_location_assignment PIN_A24 -to PEX8311_BIGEND[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_BIGEND[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_BIGEND[0]
	set_location_assignment PIN_A21 -to PEX8311_BREQI[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_BREQI[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_BREQI[0]
	set_location_assignment PIN_H17 -to PEX8311_BREQO[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_BREQO[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_BREQO[0]
	set_location_assignment PIN_C23 -to PEX8311_LLOCKO[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LLOCKO[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LLOCKO[0]
	set_location_assignment PIN_B24 -to PEX8311_LLOCKI[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LLOCKI[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LLOCKI[0]
	set_location_assignment PIN_E16 -to PEX8311_WAIT[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_WAIT[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_WAIT[0]
	set_location_assignment PIN_F18 -to PEX8311_CCS[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_CCS[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_CCS[0]
	set_location_assignment PIN_A12 -to PEX8311_LWR[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LWR[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LWR[0]
	set_location_assignment PIN_B20 -to PEX8311_BTERM[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_BTERM[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_BTERM[0]
	set_location_assignment PIN_B22 -to PEX8311_LINTO[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LINTO[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LINTO[0]
	set_location_assignment PIN_A23 -to PEX8311_LINTI[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_LINTI[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_LINTI[0]
	
	set_location_assignment PIN_D21 -to PEX8311_DREQ[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_DREQ[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_DREQ[0]
	set_location_assignment PIN_B21 -to PEX8311_DREQ[1]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_DREQ[1]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_DREQ[1]
	
	set_location_assignment PIN_D20 -to PEX8311_DACK[0]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_DACK[0]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_DACK[0]
	set_location_assignment PIN_E20 -to PEX8311_DACK[1]
	set_instance_assignment -name IO_STANDARD "3.3V LVCMOS" -to PEX8311_DACK[1]
	set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to PEX8311_DACK[1]
	
	